apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.migrationAdmin.name }}
type: Opaque
data:
{{- with .Values.migrationAdmin.env }}
{{- range $key, $value := . }}
  {{ $key | toYaml }}: {{ $value | b64enc | toYaml }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.migrationBackendOp.name }}
type: Opaque
data:
{{- with .Values.migrationBackendOp.env }}
{{- range $key, $value := . }}
  {{ $key | toYaml }}: {{ $value | b64enc | toYaml }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.migrationBackendBase.name }}
type: Opaque
data:
{{- with .Values.migrationBackendBase.env }}
{{- range $key, $value := . }}
  {{ $key | toYaml }}: {{ $value | b64enc | toYaml }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.signerBackendOp.name }}
type: Opaque
data:
{{- with .Values.signerBackendOp.env }}
{{- range $key, $value := . }}
  {{ $key | toYaml }}: {{ $value | b64enc | toYaml }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.signerBackendBase.name }}
type: Opaque
data:
{{- with .Values.signerBackendBase.env }}
{{- range $key, $value := . }}
  {{ $key | toYaml }}: {{ $value | b64enc | toYaml }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.likenftIndexer.name }}
type: Opaque
data:
{{- with .Values.likenftIndexer.env }}
{{- range $key, $value := . }}
  {{ $key | toYaml }}: {{ $value | b64enc | toYaml }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.likecollectiveIndexer.name }}
type: Opaque
data:
{{- with .Values.likecollectiveIndexer.env }}
{{- range $key, $value := . }}
  {{ $key | toYaml }}: {{ $value | b64enc | toYaml }}
{{- end }}
{{- end }}
