apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.migrationBackend.name }}
type: Opaque
data:
{{- with .Values.migrationBackend.env }}
{{- range $key, $value := . }}
  {{ $key | toYaml }}: {{ $value | b64enc | toYaml }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.signerBackend.name }}
type: Opaque
data:
{{- with .Values.signerBackend.env }}
{{- range $key, $value := . }}
  {{ $key | toYaml }}: {{ $value | b64enc | toYaml }}
{{- end }}
{{- end }}
