apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.likecoin.migration.backend.name }}
type: Opaque
data:
{{- with .Values.likecoin.migration.backend.env }}
{{- range $key, $value := . }}
  {{ $key | toYaml }}: {{ $value | b64enc | toYaml }}
{{- end }}
{{- end }}
