services:
  psql_bp:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: pg_isready -d ${DB_DATABASE} -U ${DB_USERNAME} -p 5432 -h localhost
      interval: 1s
      timeout: 1s
      retries: 30
    volumes:
      - psql_volume_bp:/var/lib/postgresql/data

  psql_bp_timescale:
    image: timescale/timescaledb-ha:pg16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_TIMESCALE_DATABASE}
      POSTGRES_USER: ${DB_TIMESCALE_USERNAME}
      POSTGRES_PASSWORD: ${DB_TIMESCALE_PASSWORD}
    ports:
      - "${DB_TIMESCALE_PORT}:5432"
    healthcheck:
      test: pg_isready -d ${DB_TIMESCALE_DATABASE} -U ${DB_TIMESCALE_USERNAME} -p 5432 -h localhost
      interval: 1s
      timeout: 1s
      retries: 30
    volumes:
      - psql_volume_bp_timescale:/var/lib/postgresql/data

  api:
    profiles: [api]
    image: golang:1.23.5
    working_dir: /src
    volumes:
      - .:/src
      - go-build-cache:/root/.cache
      - go-mod-cache:/go/pkg/mod
    ports:
      - "8091:8091"
    command: go run ./cmd/api

  process-evm-event:
    profiles: [worker]
    image: golang:1.23.5
    depends_on:
      - redis
      - psql_bp
    working_dir: /src
    volumes:
      - .:/src
      - go-build-cache:/root/.cache
      - go-mod-cache:/go/pkg/mod
    command:
      - go
      - run
      - ./cmd/worker
      - worker
      - --concurrency
      - "1"
      - check-received-evm-events
      - process-evm-event

  scheduler-all-in-one:
    profiles: [scheduler]
    image: golang:1.23.5
    depends_on:
      - redis
      - psql_bp
    working_dir: /src
    volumes:
      - .:/src
      - go-build-cache:/root/.cache
      - go-mod-cache:/go/pkg/mod
    command:
      - go
      - run
      - ./cmd/worker
      - scheduler
      - --cron
      - "*/1 * * * *"
      - check-received-evm-events

  redis:
    image: redis
    restart: always
    ports:
      - 6379
    volumes:
      - redis_data:/data

volumes:
  psql_volume_bp:
  psql_volume_bp_timescale:
  redis_data:
    driver: local
  go-build-cache:
    driver: local
  go-mod-cache:
    driver: local
