services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - pip:/root/.cache/pip
    command: [
      "poetry",
      "run",
      "fastapi",
      "dev",
      "--host",
      "0.0.0.0",
      "--port",
      "8000",
      "staking_image/server.py",
    ]

volumes:
  pip:
