cosmosLikeCoinNetworkConfig:
  path: "dev/cosmos-likecoin-network.json"

likecoinMigration:
  configFilePath: "dev/likecoin/migration/frontend/config.json"
  nginxConfigFilePath: "dev/likecoin/migration/frontend/nginx/nginx.conf"

  ingress:
    host: likecoin-migration.pandawork.com
    tls:
      secretName: likecoin-migration.pandawork.com
      host: likecoin-migration.pandawork.com

likenftMigration:
  configFilePath: "dev/likenft/migration/frontend/config.json"
  nginxConfigFilePath: "dev/likenft/migration/frontend/nginx/nginx.conf"

  ingress:
    host: likenft-migration.pandawork.com
    tls:
      secretName: likenft-migration.pandawork.com
      host: likenft-migration.pandawork.com

migrationBackend:
  env:
    COSMOS_NODE_URL: https://node.testnet.like.co
    ROUTE_PREFIX: ""
    ETH_NETWORK_PUBLIC_RPC_URL: https://sepolia.optimism.io
    ETH_SIGNER_BASE_URL: http://signer-backend
    ETH_TOKEN_ADDRESS: "0x0FE55BE56FDDafD0A6Eaf6D28e7F26ACFf1C51f0"
    ETH_LIKENFT_CONTRACT_ADDRESS: "0x01B25559B03AA22458d286C99b9fFfd4400ad093"
    LIKECOIN_API_URL_BASE: https://api.rinkeby.like.co
    WORKER_CONCURRENCY: "1"
    INITIAL_NEW_CLASS_OWNER: "0xA515ffD6A6889f2CCCb576cEcA2a33f60129eBFD"
    INITIAL_NEW_CLASS_MINTER: "0xA515ffD6A6889f2CCCb576cEcA2a33f60129eBFD"
    INITIAL_NEW_CLASS_UPDATER: "0xA515ffD6A6889f2CCCb576cEcA2a33f60129eBFD"
    INITIAL_BATCH_MINT_NFTS_OWNER: "0xA515ffD6A6889f2CCCb576cEcA2a33f60129eBFD"
    LIKECOIN_BURNING_COSMOS_ADDRESS: "like155s3xuruk2vnynda9gq6x9e7uzvut74654mc4d"

  ingress:
    host: like-migration-api.pandawork.com
    tls:
      secretName: like-migration-api.pandawork.com
      host: like-migration-api.pandawork.com

signerBackend:
  env:
    ROUTE_PREFIX: ""
    ETH_NETWORK_PUBLIC_RPC_URL: https://sepolia.optimism.io

likenftIndexer:
  env:
    ETH_NETWORK_PUBLIC_RPC_URL: https://sepolia.optimism.io
    ETH_LIKE_PROTOCOL_CONTRACT_ADDRESS: "0x01B25559B03AA22458d286C99b9fFfd4400ad093"
    PORT: "8091"

  api:
    ingress:
      host: likenft-indexer.pandawork.com
      tls:
        secretName: likenft-indexer.pandawork.com
        host: likenft-indexer.pandawork.com
