cosmosLikeCoinNetworkConfig:
  path: "dev/cosmos-likecoin-network.json"

likecoinMigration:
  container:
    imageRepository: oursky/likecoin-migration
  configFilePath: "dev/likecoin-migration-config.json"
  nginxConfigFilePath: "dev/nginx.conf"

  ingress:
    host: likecoin-migration.pandawork.com
    tls:
      secretName: likecoin-migration.pandawork.com
      host: likecoin-migration.pandawork.com

likenftMigration:
  container:
    imageRepository: oursky/likenft-migration
  configFilePath: "dev/likenft-migration-config.json"
  nginxConfigFilePath: "dev/nginx.conf"

  ingress:
    host: likenft-migration.pandawork.com
    tls:
      secretName: likenft-migration.pandawork.com
      host: likenft-migration.pandawork.com

migrationAdmin:
  container:
    imageRepository: oursky/migration-admin
  configFilePath: "dev/migration-admin-config.json"
  nginxConfigFilePath: "dev/nginx.conf"

  ingress:
    annotations:
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: basic-auth
      nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - LikeProtocol'
    host: like-migration-admin.pandawork.com
    tls:
      secretName: like-migration-admin.pandawork.com
      host: like-migration-admin.pandawork.com

migrationBackend:
  container:
    imageRepository: oursky/like-migration-backend
  env:
    SENTRY_DSN: https://42c026a5b18a5546d1eff10d29ec01f9@o21224.ingest.us.sentry.io/4509349416534016
    SENTRY_DEBUG: "true"
    COSMOS_NODE_URL: https://node.testnet.like.co
    COSMOS_NODE_HTTP_TIMEOUT_SECONDS: "60"
    ROUTE_PREFIX: ""
    ETH_SIGNER_BASE_URL: http://signer-backend
    ETH_TOKEN_ADDRESS: "0x0FE55BE56FDDafD0A6Eaf6D28e7F26ACFf1C51f0"
    ETH_LIKENFT_CONTRACT_ADDRESS: "0x67BCd74981c33E95E5e306085754DD0A721183F1"
    LIKECOIN_API_URL_BASE: https://api.rinkeby.like.co
    LIKECOIN_API_HTTP_TIMEOUT_SECONDS: "60"
    WORKER_CONCURRENCY: "1"
    INITIAL_NEW_CLASS_OWNER: "0xA515ffD6A6889f2CCCb576cEcA2a33f60129eBFD"
    INITIAL_NEW_CLASS_MINTER: "0xA515ffD6A6889f2CCCb576cEcA2a33f60129eBFD"
    INITIAL_NEW_CLASS_UPDATER: "0xA515ffD6A6889f2CCCb576cEcA2a33f60129eBFD"
    INITIAL_BATCH_MINT_NFTS_OWNER: "0xA515ffD6A6889f2CCCb576cEcA2a33f60129eBFD"
    BATCH_MINT_ITEM_PER_PAGE: "10"
    LIKECOIN_BURNING_COSMOS_ADDRESS: "like155s3xuruk2vnynda9gq6x9e7uzvut74654mc4d"

  ingress:
    host: like-migration-api.pandawork.com
    tls:
      secretName: like-migration-api.pandawork.com
      host: like-migration-api.pandawork.com

signerBackend:
  container:
    imageRepository: oursky/like-signer-backend
  env:
    SENTRY_DSN: https://09eb616dbe039a14c95a24f84003493a@o21224.ingest.us.sentry.io/4509349425905664
    SENTRY_DEBUG: "true"
    ROUTE_PREFIX: ""

likenftIndexer:
  container:
    imageRepository: oursky/likenft-indexer
  env:
    SENTRY_DSN: https://77cbd727e7667e05e0d1942037a06de6@o21224.ingest.us.sentry.io/4509349428199424
    SENTRY_DEBUG: "true"
    ETH_LIKE_PROTOCOL_CONTRACT_ADDRESS: "0x67BCd74981c33E95E5e306085754DD0A721183F1"
    EVM_EVENT_LIKE_PROTOCOL_INITIAL_BLOCK_HEIGHT: "25837814"
    EVM_EVENT_QUERY_NUMBER_OF_BLOCKS_LIMIT: "500"
    PORT: "8091"

  api:
    ingress:
      host: likenft-indexer.pandawork.com
      tls:
        secretName: likenft-indexer.pandawork.com
        host: likenft-indexer.pandawork.com
