cosmosLikeCoinNetworkConfig:
  name: likecoin-network

likecoinMigration:
  name: likecoin-migration

  container:
    imageRepository: likecoin/likecoin-migration
    imagePullPolicy: IfNotPresent
    port: 80
    restartPolicy: Always

  service:
    port: 80
  ingress:
    prefix: /
    tls:
      secretName: tls-likecoin-migration

  resources: {}

likenftMigration:
  name: likenft-migration

  container:
    imageRepository: likecoin/likenft-migration
    imagePullPolicy: IfNotPresent
    port: 80
    restartPolicy: Always

  service:
    port: 80
  ingress:
    prefix: /
    tls:
      secretName: tls-likenft-migration

  resources: {}

migrationAdmin:
  name: migration-admin
  
  initContainer:
    imageRepository: nginx:alpine
    imagePullPolicy: IfNotPresent
    
  container:
    imageRepository: likecoin/migration-admin
    imagePullPolicy: IfNotPresent
    port: 80
    restartPolicy: Always

  service:
    port: 80
  ingress:
    prefix: /
    adminPrefix: /admin
    tls:
      secretName: tls-migration-admin

  resources: {}

migrationBackend:
  name: migration-backend
  env:
    BATCH_MINT_ITEM_PER_PAGE: "10"
    CLASS_MIGRATION_ESTIMATED_DURATION_SECONDS: "2"
    NFT_MIGRATION_ESTIMATED_DURATION_SECONDS: "2"
    SHOULD_PREMINT_ALL_NFTS_WHEN_NEW_CLASS: "true"
    PREMINT_ALL_NFTS_WHEN_NEW_CLASS_SHOULD_PREMINT_ARBITRARY_NFTIDS: "false"

  container:
    imageRepository: likecoin/like-migration-backend
    imagePullPolicy: IfNotPresent
    port: 8091

  migrate: {}

  service:
    port: 80
  ingress:
    prefix: /
    adminPrefix: /admin
    tls:
      secretName: tls-migration-backend

  resources: {}

  worker:
    name: migration-backend-worker

    resources: {}

  scheduler:
    name: migration-backend-scheduler

    resources: {}

signerBackend:
  name: signer-backend

  migrate:
    backoffLimit: {}

  container:
    imageRepository: likecoin/like-signer-backend
    imagePullPolicy: IfNotPresent
    port: 8091

  service:
    port: 80

  resources: {}

  worker:
    name: signer-backend-worker

    resources: {}

  scheduler:
    name: signer-backend-scheduler

    resources: {}

likenftIndexer:
  name: likenft-indexer

  container:
    imageRepository: likecoin/likenft-indexer
    imagePullPolicy: IfNotPresent

  migrate: {}

  api:
    name: likenft-indexer-api

    container:
      port: 8091

    service:
      port: 80
    ingress:
      prefix: /
      tls:
        secretName: tls-likenft-indexer

    resources: {}

  env:
    # Assume there are 100 booknfts and the scheduler will schedule the fan out job per 1 minute
    TASK_ACQUIRE_BOOK_NFT_EVENTS_MAX_QUEUE_LENGTH: "100"
    TASK_ACQUIRE_BOOK_NFT_EVENTS_NEXT_PROCESSING_SCORE_BLOCK_HEIGHT_CONTRIBUTION: "0.00000001"
    TASK_ACQUIRE_BOOK_NFT_EVENTS_NEXT_PROCESSING_SCORE_WEIGHT_0_CONSTANT: "10"
    TASK_ACQUIRE_BOOK_NFT_EVENTS_NEXT_PROCESSING_SCORE_WEIGHT_1_CONSTANT: "1"
    TASK_ACQUIRE_BOOK_NFT_EVENTS_NEXT_PROCESSING_SCORE_WEIGHT_CONTRIBUTION: "60"
    TASK_ACQUIRE_BOOK_NFT_EVENTS_IN_PROGRESS_TIMEOUT_SECONDS: "6000"
    TASK_ACQUIRE_BOOK_NFT_EVENTS_RETRY_INITIAL_TIMEOUT_SECONDS: "300"
    TASK_ACQUIRE_BOOK_NFT_EVENTS_RETRY_EXPONENTIAL_BACKOFF_COEFF: "2"
    TASK_ACQUIRE_BOOK_NFT_EVENTS_RETRY_MAX_TIMEOUT_SECONDS: "3600"

  worker:
    name: likenft-indexer-worker

    deployments:
      periodic:
        resources: {}
        tasks:
          - acquire-book-nft-events
          - acquire-like-protocol-events
          - check-like-protocol
          - check-received-evm-events
      check-book-nfts:
        resources: {}
        tasks:
          - check-book-nfts
          - acquire-book-nft-events-with-lifecycle
      process-evm-event:
        resources: {}
        tasks:
          - process-evm-event
      index-action-request:
        resources: {}
        tasks:
          - index-action-check-book-nft
          - index-action-check-like-protocol
      index-action-process-evm-event:
        resources: {}
        tasks:
          - index-action-process-evm-event
          - index-action-check-received-evm-events

  scheduler:
    name: likenft-indexer-scheduler

    deployments:
      all-in-one:
        cron: "*/1 * * * *"
        tasks:
          - check-book-nfts
          - check-like-protocol
          - check-received-evm-events
        resources: {}

redis:
  name: redis
  container:
    imageRepository: redis
    imageVersion: 7
    port: 6379

  service:
    port: 6379

  resources: {}

nginx:
  name: nginx

  container:
    image: nginx
    imagePullPolicy: IfNotPresent
    port: 8000
    restartPolicy: Always

  service:
    port: 80

ingress:
  name: likecoin-op

  className: "nginx"

  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/use-regex: "true"
