cosmosLikeCoinNetworkConfig:
  name: likecoin-network

likecoinMigration:
  name: likecoin-migration

  container:
    imageRepository: chankiyu22/likecoin-migration
    imagePullPolicy: IfNotPresent
    port: 80
    restartPolicy: Always

  service:
    port: 80

  resources: {}

likenftMigration:
  name: likenft-migration

  container:
    imageRepository: chankiyu22/likenft-migration
    imagePullPolicy: IfNotPresent
    port: 80
    restartPolicy: Always

  service:
    port: 80

  resources: {}

migrationBackend:
  name: migration-backend

  container:
    imageRepository: chankiyu22/like-migration-backend
    imagePullPolicy: IfNotPresent
    port: 8091

  service:
    port: 80

  resources: {}

  worker:
    name: migration-backend-worker

    resources: {}

  scheduler:
    name: migration-backend-scheduler

    resources: {}

signerBackend:
  name: signer-backend

  container:
    imageRepository: chankiyu22/like-signer-backend
    imagePullPolicy: IfNotPresent
    port: 8091

  service:
    port: 80

  resources: {}

  worker:
    name: signer-backend-worker

    resources: {}

  scheduler:
    name: signer-backend-scheduler

    resources: {}

likenftIndexer:
  name: likenft-indexer

  container:
    imageRepository: chankiyu22/likenft-indexer
    imagePullPolicy: IfNotPresent

  worker:
    name: likenft-indexer-worker

    resources: {}

  scheduler:
    name: likenft-indexer-scheduler

    resources: {}

redis:
  name: redis
  container:
    imageRepository: redis
    imageVersion: 7
    port: 6379

  service:
    port: 6379

  resources: {}

nginx:
  name: nginx

  container:
    image: nginx
    imagePullPolicy: IfNotPresent
    port: 8000
    restartPolicy: Always

  service:
    port: 80

ingress:
  name: likecoin-op

  className: "nginx"

  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/use-regex: "true"
