parser:
  allow_remote: false

generator:
  # `auto` (default) generates `NewError` if possible
  # `on` tells generator to fail if spec does not meet requirements
  # `off` disables `Convenient errors` at all
  convenient_errors: "on"
