name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  likecoin:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: make -C likecoin3 setup

      - run: make -C likecoin3 ci

  likenft:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: make -C likenft setup

      - run: make -C likenft ci

  likecoin-migration:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: make -C likecoin-migration setup

      - run: make -C likecoin-migration ci

  likenft-migrate:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: make -C likenft-migration setup

      - run: make -C likenft-migration ci

  migration-backend:
    runs-on: [ubuntu-latest]

    services:
      docker:
        image: docker:dind
        options: --privileged --shm-size=2g
        ports:
          - 2375:2375

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.10

      - run: make -C migration-backend vendor

      - run: make -C migration-backend ci

  signer-backend:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.10

      - run: make -C signer-backend vendor

      - run: make -C signer-backend ci

  migration-admin:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: make -C migration-admin setup

      - run: make -C migration-admin ci

  likecollective-indexer:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x

      - run: make -C likecollective-indexer vendor

      - run: make -C likecollective-indexer ci

