name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  likecoin:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: make -C likecoin setup

      - run: make -C likecoin ci

  likenft:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: make -C likenft setup

      - run: make -C likenft ci

  likecoin-migration:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: make -C likecoin-migration setup

      - run: make -C likecoin-migration ci

  likenft-migrate:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: make -C likenft-migration setup

      - run: make -C likenft-migration ci
